# 0605 데이터 추가 변환 처리 및 모델 진행

In [1]:
import pandas as pd

df1 = pd.read_csv('seoul_final.csv',encoding='cp949')
df2 = pd.read_csv('seoul_final (2).csv',encoding='cp949')

In [2]:
df1 = df1.drop(columns=['Unnamed: 0'])
df2 = df2.drop(columns=['Unnamed: 0'])

In [3]:
df1

    자치구       승하차   노인인구  경로당  노인시설  노인시설정원
0    17  15540698  93309  172    29     670
1     0  17425049  74959  167    32     215
2     1  11581597  69903  121    22     619
3    14  11696077  60072  141    14     322
4     8  12334867  85420  243    29    1008
5     3   8317204  88733  218    49    1042
6    19   6448615  60663  174    29     118
7     4   9236593  78430  114    30     435
8    16   6467009  73613  175    31     715
9    21  12361204  85010  154    40    1095
10   10  10266951  61612  134    21     224
11   24   5719284  69341  127    26     859
12    6   8048800  69201  199    32     913
13   22  22039837  28311   63    21     404
14   12   5881397  54002  154    17     284
15   11  10736494  64928  140    14     190
16   23  16276987  24174   48     8      74
17    9   5119901  62009  135    36     874
18    2   5709043  63313  100    26     503
19    5   9415599  50311   95    20    1247
20   18   4185988  65541  164    40     656
21   13   4959137  53756  111    26     388
22   15   7078565  45435  162    20     391
23   20   6693008  39779   88    25     194
24    7    916795  39314   73    24     678

In [4]:
df2

     자치구       승하차   노인인구  경로당  노인시설  노인시설정원
0    송파구  15540698  93309  172    29     670
1    강남구  17425049  74959  167    32     215
2    강동구  11581597  69903  121    22     619
3    서초구  11696077  60072  141    14     322
4    노원구  12334867  85420  243    29    1008
5    강서구   8317204  88733  218    49    1042
6   영등포구   6448615  60663  174    29     118
7    관악구   9236593  78430  114    30     435
8    성북구   6467009  73613  175    31     715
9    은평구  12361204  85010  154    40    1095
10  동대문구  10266951  61612  134    21     224
11   중랑구   5719284  69341  127    26     859
12   구로구   8048800  69201  199    32     913
13   종로구  22039837  28311   63    21     404
14   마포구   5881397  54002  154    17     284
15   동작구  10736494  64928  140    14     190
16    중구  16276987  24174   48     8      74
17   도봉구   5119901  62009  135    36     874
18   강북구   5709043  63313  100    26     503
19   광진구   9415599  50311   95    20    1247
20   양천구   4185988  65541  164    40     656
21  서대문구   4959137  53756  111    26     388
22   성동구   7078565  45435  162    20     391
23   용산구   6693008  39779   88    25     194
24   금천구    916795  39314   73    24     678

In [5]:
df2['총노인시설'] = df2['경로당'] + df2['노인시설']
df2

     자치구       승하차   노인인구  경로당  노인시설  노인시설정원  총노인시설
0    송파구  15540698  93309  172    29     670    201
1    강남구  17425049  74959  167    32     215    199
2    강동구  11581597  69903  121    22     619    143
3    서초구  11696077  60072  141    14     322    155
4    노원구  12334867  85420  243    29    1008    272
5    강서구   8317204  88733  218    49    1042    267
6   영등포구   6448615  60663  174    29     118    203
7    관악구   9236593  78430  114    30     435    144
8    성북구   6467009  73613  175    31     715    206
9    은평구  12361204  85010  154    40    1095    194
10  동대문구  10266951  61612  134    21     224    155
11   중랑구   5719284  69341  127    26     859    153
12   구로구   8048800  69201  199    32     913    231
13   종로구  22039837  28311   63    21     404     84
14   마포구   5881397  54002  154    17     284    171
15   동작구  10736494  64928  140    14     190    154
16    중구  16276987  24174   48     8      74     56
17   도봉구   5119901  62009  135    36     874    171
18   강북구   5709043  63313  100    26     503    126
19   광진구   9415599  50311   95    20    1247    115
20   양천구   4185988  65541  164    40     656    204
21  서대문구   4959137  53756  111    26     388    137
22   성동구   7078565  45435  162    20     391    182
23   용산구   6693008  39779   88    25     194    113
24   금천구    916795  39314   73    24     678     97

In [6]:
df2['인구대비시설'] = df2['총노인시설'] / df2['노인인구']
df2['승하차대비시설'] = df2['총노인시설'] / df2['승하차']
df2['인구승하차대비시설'] = df2['총노인시설'] / (df2['노인인구']*df2['승하차'])
df2

,자치구,승하차,노인인구,경로당,노인시설,노인시설정원,총노인시설,인구대비시설,승하차대비시설,인구승하차대비시설
0,송파구,15540698,93309,172,29,670,201,0.002154,0.000013,1.386124e-10
1,강남구,17425049,74959,167,32,215,199,0.002655,0.000011,1.523545e-10
2,강동구,11581597,69903,121,22,619,143,0.002046,0.000012,1.766330e-10
3,서초구,11696077,60072,141,14,322,155,0.002580,0.000013,2.206071e-10
4,노원구,12334867,85420,243,29,1008,272,0.003184,0.000022,2.581516e-10
5,강서구,8317204,88733,218,49,1042,267,0.003009,0.000032,3.617835e-10
6,영등포구,6448615,60663,174,29,118,203,0.003346,0.000031,5.189263e-10
7,관악구,9236593,78430,114,30,435,144,0.001836,0.000016,1.987781e-10
8,성북구,6467009,73613,175,31,715,206,0.002798,0.000032,4.327223e-10
9,은평구,12361204,85010,154,40,1095,194,0.002282,0.000016,1.846167e-10
10,동대문구,10266951,61612,134,21,224,155,0.002516,0.000015,2.450332e-10
11,중랑구,5719284,69341,127,26,859,153,0.002206,0.000027,3.857977e-10
12,구로구,8048800,69201,199,32,913,231,0.003338,0.000029,4.147329e-10
13,종로구,22039837,28311,63,21,404,84,0.002967,0.000004,1.346219e-10
14,마포구,5881397,54002,154,17,284,171,0.003167,0.000029,5.384009e-10
15,동작구,10736494,64928,140,14,190,154,0.002372,0.000014,2.209155e-10
16,중구,16276987,24174,48,8,74,56,0.002317,0.000003,1.423199e-10
17,도봉구,5119901,62009,135,36,874,171,0.002758,0.000033,5.386167e-10
18,강북구,5709043,63313,100,26,503,126,0.001990,0.000022,3.485895e-10
19,광진구,9415599,50311,95,20,1247,115,0.002286,0.000012,2.427655e-10
20,양천구,4185988,65541,164,40,656,204,0.003113,0.000049,7.435653e-10
21,서대문구,4959137,53756,111,26,388,137,0.002549,0.000028,5.139105e-10
22,성동구,7078565,45435,162,20,391,182,0.004006,0.000026,5.658947e-10
23,용산구,6693008,39779,88,25,194,113,0.002841,0.000017,4.244272e-10
24,금천구,916795,39314,73,24,678,97,0.002467,0.000106,2.691239e-09

In [7]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# 정규화할 열 선택
column_to_normalize = ['인구승하차대비시설']

# 정규화를 위한 MinMaxScaler 객체 생성
scaler = MinMaxScaler()

# 정규화할 열에 대해 fit_transform 수행
df2[column_to_normalize] = scaler.fit_transform(df2[column_to_normalize])

# 정규화된 데이터 확인
df2

,자치구,승하차,노인인구,경로당,노인시설,노인시설정원,총노인시설,인구대비시설,승하차대비시설,인구승하차대비시설
0,송파구,15540698,93309,172,29,670,201,0.002154,0.000013,0.001561
1,강남구,17425049,74959,167,32,215,199,0.002655,0.000011,0.006936
2,강동구,11581597,69903,121,22,619,143,0.002046,0.000012,0.016432
3,서초구,11696077,60072,141,14,322,155,0.002580,0.000013,0.033632
4,노원구,12334867,85420,243,29,1008,272,0.003184,0.000022,0.048318
5,강서구,8317204,88733,218,49,1042,267,0.003009,0.000032,0.088852
6,영등포구,6448615,60663,174,29,118,203,0.003346,0.000031,0.150318
7,관악구,9236593,78430,114,30,435,144,0.001836,0.000016,0.025094
8,성북구,6467009,73613,175,31,715,206,0.002798,0.000032,0.116600
9,은평구,12361204,85010,154,40,1095,194,0.002282,0.000016,0.019555
10,동대문구,10266951,61612,134,21,224,155,0.002516,0.000015,0.043186
11,중랑구,5719284,69341,127,26,859,153,0.002206,0.000027,0.098245
12,구로구,8048800,69201,199,32,913,231,0.003338,0.000029,0.109563
13,종로구,22039837,28311,63,21,404,84,0.002967,0.000004,0.000000
14,마포구,5881397,54002,154,17,284,171,0.003167,0.000029,0.157935
15,동작구,10736494,64928,140,14,190,154,0.002372,0.000014,0.033753
16,중구,16276987,24174,48,8,74,56,0.002317,0.000003,0.003011
17,도봉구,5119901,62009,135,36,874,171,0.002758,0.000033,0.158019
18,강북구,5709043,63313,100,26,503,126,0.001990,0.000022,0.083692
19,광진구,9415599,50311,95,20,1247,115,0.002286,0.000012,0.042299
20,양천구,4185988,65541,164,40,656,204,0.003113,0.000049,0.238183
21,서대문구,4959137,53756,111,26,388,137,0.002549,0.000028,0.148356
22,성동구,7078565,45435,162,20,391,182,0.004006,0.000026,0.168689
23,용산구,6693008,39779,88,25,194,113,0.002841,0.000017,0.113355
24,금천구,916795,39314,73,24,678,97,0.002467,0.000106,1.000000

In [9]:
df2.columns

Index(['자치구', '승하차', '노인인구', '경로당', '노인시설', '노인시설정원', '총노인시설', '인구대비시설',
       '승하차대비시설', '인구승하차대비시설'],
      dtype='object')

모델을 구축하기 위해 해당 특성 열을 사용하여 노인 인프라의 부족 여부를 나타내는 타겟 변수를 예측하는 분류 모델 사용가능
- 분류 모델은 자치구별 특성을 기반으로 노인 인프라의 부족 여부를 예측하는 데 도움 준다

In [10]:
import pandas as pd

# 예측에 사용할 특성 열 선택
features = ['자치구', '승하차', '노인인구', '경로당', '노인시설', '노인시설정원']

# 선택한 특성 열만 포함된 DataFrame 생성
df_selected = df1[features]

# 각 특성 열에 대해 내림차순으로 순위 매기기
rank_df = df_selected.rank(ascending=False, method='min')

# 순위 결과 출력
rank_df

     자치구   승하차  노인인구   경로당  노인시설  노인시설정원
0    8.0   4.0   1.0   6.0   9.0    10.0
1   25.0   2.0   6.0   7.0   5.0    21.0
2   24.0   8.0   8.0  17.0  17.0    12.0
3   11.0   7.0  17.0  12.0  23.0    18.0
4   17.0   6.0   3.0   1.0   9.0     4.0
5   22.0  13.0   2.0   2.0   1.0     3.0
6    6.0  18.0  16.0   5.0   9.0    24.0
7   21.0  12.0   5.0  18.0   8.0    14.0
8    9.0  17.0   7.0   4.0   7.0     8.0
9    4.0   5.0   4.0  10.0   2.0     2.0
10  15.0  10.0  15.0  15.0  18.0    20.0
11   1.0  20.0   9.0  16.0  12.0     7.0
12  19.0  14.0  10.0   3.0   5.0     5.0
13   3.0   1.0  24.0  24.0  18.0    15.0
14  13.0  19.0  18.0  10.0  22.0    19.0
15  14.0   9.0  12.0  13.0  23.0    23.0
16   2.0   3.0  25.0  25.0  25.0    25.0
17  16.0  22.0  14.0  14.0   4.0     6.0
18  23.0  21.0  13.0  20.0  12.0    13.0
19  20.0  11.0  20.0  21.0  20.0     1.0
20   7.0  24.0  11.0   8.0   2.0    11.0
21  12.0  23.0  19.0  19.0  12.0    17.0
22  10.0  15.0  21.0   9.0  20.0    16.0
23   5.0  16.0  22.0  22.0  15.0    22.0
24  18.0  25.0  23.0  23.0  16.0     9.0

# 최종

In [20]:
df3 = pd.read_csv('seoul_ver1.csv', encoding='cp949')
df3

,자치구,승하차,지하철역수,노인인구,경로당,노인시설,노인시설정원,총노인시설,인구대비시설,승하차대비시설,인구승하차대비시설,역수대비승하차,노인인프라구축현황,레이블
0,송파구,15540698,18,93309,172,29,670,201,0.002154,0.000013,0.001561,8.633721e+05,1859.818392,0
1,강남구,17425049,17,74959,167,32,215,199,0.002655,0.000011,0.006936,1.025003e+06,2721.161883,1
2,강동구,11581597,22,69903,121,22,619,143,0.002046,0.000012,0.016432,5.264362e+05,1076.926319,0
3,서초구,11696077,10,60072,141,14,322,155,0.002580,0.000013,0.033632,1.169608e+06,3017.865120,1
4,노원구,12334867,14,85420,243,29,1008,272,0.003184,0.000022,0.048318,8.810619e+05,2805.535525,1
5,강서구,8317204,9,88733,218,49,1042,267,0.003009,0.000032,0.088852,9.241338e+05,2780.743564,1
6,영등포구,6448615,12,60663,174,29,118,203,0.003346,0.000031,0.150318,5.373846e+05,1798.280178,0
7,관악구,9236593,4,78430,114,30,435,144,0.001836,0.000016,0.025094,2.309148e+06,4239.670381,1
8,성북구,6467009,9,73613,175,31,715,206,0.002798,0.000032,0.116600,7.185566e+05,2010.822143,0
9,은평구,12361204,11,85010,154,40,1095,194,0.002282,0.000016,0.019555,1.123746e+06,2564.482869,1
10,동대문구,10266951,9,61612,134,21,224,155,0.002516,0.000015,0.043186,1.140772e+06,2869.890795,1
11,중랑구,5719284,9,69341,127,26,859,153,0.002206,0.000027,0.098245,6.354760e+05,1402.169395,0
12,구로구,8048800,10,69201,199,32,913,231,0.003338,0.000029,0.109563,8.048800e+05,2686.771578,1
13,종로구,22039837,12,28311,63,21,404,84,0.002967,0.000004,0.000000,1.836653e+06,5449.431634,1
14,마포구,5881397,14,54002,154,17,284,171,0.003167,0.000029,0.157935,4.200998e+05,1330.266719,0
15,동작구,10736494,13,64928,140,14,190,154,0.002372,0.000014,0.033753,8.258842e+05,1958.879985,0
16,중구,16276987,14,24174,48,8,74,56,0.002317,0.000003,0.003011,1.162642e+06,2693.304708,1
17,도봉구,5119901,6,62009,135,36,874,171,0.002758,0.000033,0.158019,8.533168e+05,2353.161291,0
18,강북구,5709043,4,63313,100,26,503,126,0.001990,0.000022,0.083692,1.427261e+06,2840.409624,1
19,광진구,9415599,9,50311,95,20,1247,115,0.002286,0.000012,0.042299,1.046178e+06,2391.334533,0
20,양천구,4185988,5,65541,164,40,656,204,0.003113,0.000049,0.238183,8.371976e+05,2605.823994,1
21,서대문구,4959137,5,53756,111,26,388,137,0.002549,0.000028,0.148356,9.918274e+05,2527.724418,1
22,성동구,7078565,13,45435,162,20,391,182,0.004006,0.000026,0.168689,5.445050e+05,2181.135908,0
23,용산구,6693008,10,39779,88,25,194,113,0.002841,0.000017,0.113355,6.693008e+05,1901.279328,0
24,금천구,916795,3,39314,73,24,678,97,0.002467,0.000106,1.000000,3.055983e+05,754.007182,0

# 1. 로지스틱회귀

In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score, mean_squared_error, r2_score

# 예측에 사용할 특성 열 선택
features = ['자치구', '승하차', '노인인구', '총노인시설', '노인시설정원','노인인프라구축현황']

# 원-핫 인코딩 수행
df_encoded = pd.get_dummies(df3, columns=['자치구'])

# 예측에 사용할 특성 열 선택
features_encoded = df_encoded.columns.drop(['레이블'])

# 훈련 데이터와 테스트 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(df_encoded[features_encoded], df_encoded['레이블'], test_size=0.2, random_state=42)

# 로지스틱 회귀 모델 구축
model = LogisticRegression()
model.fit(X_train, y_train)

# 예측 수행
y_pred = model.predict(X_test)

# 정확도 평가
accuracy = accuracy_score(y_test, y_pred)
print('정확도:', accuracy)

# 모델 평가
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("평균 제곱 오차(MSE): ", mse)
print("결정 계수(R^2): ", r2)

정확도: 0.8
평균 제곱 오차(MSE):  0.2
결정 계수(R^2):  -0.24999999999999956

# 2. 선형회귀

In [25]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


# 예측에 사용할 특성 열 선택
features = ['자치구', '승하차', '노인인구', '총노인시설', '노인시설정원','노인인프라구축현황']

# 원-핫 인코딩 수행
df_encoded = pd.get_dummies(df3, columns=['자치구'])

# 예측에 사용할 특성 열 선택
features_encoded = df_encoded.columns.drop(['레이블'])

# 훈련 데이터와 테스트 데이터 분할
X_train, X_test, y_train, y_test = train_test_split(df_encoded[features_encoded], df_encoded['레이블'], test_size=0.2, random_state=42)

# 모델 생성 및 훈련
model = LinearRegression()
model.fit(X_train, y_train)

# 테스트 데이터로 예측
y_pred = model.predict(X_test)

from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("평균 제곱 오차(MSE): ", mse)
print("결정 계수(R^2): ", r2)

평균 제곱 오차(MSE):  0.7369509144628791
결정 계수(R^2):  -3.6059432153929922

# 3. 랜덤 포레스트

In [26]:
from sklearn.ensemble import RandomForestRegressor

# 랜덤 포레스트 회귀 모델 구축
model = RandomForestRegressor(n_estimators=100, random_state=42)

# 모델 학습
model.fit(X_train, y_train)

# 모델 예측
y_pred = model.predict(X_test)

# 모델 평가
mse = mean_squared_error(y_test, y_pred)
print(mse)

0.00026